version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
workflows:
  default:
    jobs:
      - build-styles
      - deploy:
          requires:
            - build-styles
          filters:
            branches:
              only:
                - gh-pages

jobs:
  build-styles:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run:
          name: "Install Dependencies"
          command: npm install
      - run:
          name: "Setup Artifacts Folder"
          command: |
            mkdir ~/artifacts
            mkdir ~/artifacts/font-glyphs
      - run:
          name: "Copy Glyphs"
          command: |
            cp -r ./font-glyphs ~/artifacts/
      - run:
          name: "Generate sprites"
          command: |
            ./tools/generate_sprite_sheets
      - run:
          name: "Add files"
          command: |
            cp sprites*.json ~/artifacts/
            cp sprites*.png ~/artifacts/
            cp style.json ~/artifacts/
            cp map.html ~/artifacts/
      - persist_to_workspace:
          root: ~/artifacts
          paths:
            - "*"

  deploy:
    docker:
      - image: cimg/base:2021.11
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - add_ssh_keys:
          fingerprints:
            - "5e:b9:08:4e:01:f0:71:3c:74:0c:d9:10:3b:6d:74:de"
      - run:
          name: "SFTP upload"
          command: |
            sudo ssh-keyscan -H maps.tuerantuer.org >> known_hosts
            sftp -b - -o UserKnownHostsFile=known_hosts ci@maps.tuerantuer.org:/styles/ \<<< $'-mkdir ehrenamtskarte\n cd ehrenamtskarte\n put -r /tmp/artifacts/*'
